name: autoupdate
on:
  push: {}
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PR_LABELS: "autoupdate"
          EXCLUDED_LABELS: "wontfix"
          MERGE_MSG: "Branch was auto-updated."
          RETRY_COUNT: "1"
          MERGE_CONFLICT_ACTION: "fail"
